/** Researched unique copy — Kenmore dryer F01–F15. Sources: Kenmore 110.65132 service manual, Whirlpool dryer fault codes */
export default [
  {
    brand: "kenmore", appliance: "dryer", error_code: "f01",
    title: "Kenmore Dryer F01 Error Code",
    summary: "Main electronic control board failure",
    meta_description: "Kenmore dryer F01 EEPROM fault on main control. Unplug, reseat harnesses, replace board if code returns on power-up.",
    meaning: "F01 on Kenmore 110-series dryers means the main electronic control failed its internal memory check. Heat, motor, and moisture-sensing outputs stop until the board resets or is replaced.",
    causes: ["Lightning surge through the laundry circuit", "Loose main harness connector after moving the dryer", "Moisture corrosion on the board from a vent leak", "Failed EEPROM on the electronic control assembly"],
    fixes: ["Unplug the dryer for five minutes before restoring power", "Remove the top panel and reseat the large harness into the control board", "Inspect for burnt traces near the line input terminals", "Run a timed dry on air fluff as a board function test"],
    when_to_call_technician: "F01 that returns immediately after power-up requires a new Kenmore electronic control matched to your model suffix.",
    affected_models: ["Kenmore 110.65132410", "Kenmore 110.67822600", "Kenmore 110.60932990"],
    related_codes: ["f06", "f13", "f14"], difficulty: "hard", estimated_time: "Call technician"
  },
  {
    brand: "kenmore", appliance: "dryer", error_code: "f02",
    title: "Kenmore Dryer F02 Error Code",
    summary: "Key stuck on the user interface",
    meta_description: "Kenmore dryer F02 stuck button fault. Wipe console dry, power-cycle, replace UI if keys read pressed constantly.",
    meaning: "F02 means the console detects a keypad or touch button held continuously. The Kenmore dryer will not start a cycle while it thinks a selection key is pressed.",
    causes: ["Static discharge locking a touch pad trace", "Spilled liquid on the console membrane", "Cracked overlay shorting adjacent pads", "Failed user interface board behind the console"],
    fixes: ["Wipe the console dry with a soft cloth", "Unplug two minutes and touch each button once after restart", "Avoid leaning on the console during operation", "Replace the UI if F02 shows with no keys touched"],
    when_to_call_technician: "UI board replacement requires matching the part to your console style—order by model number from the rating plate.",
    affected_models: ["Kenmore 110.65132410", "Kenmore 110.67822600", "Kenmore 110.60932990"],
    related_codes: ["f08", "f11", "f06"], difficulty: "medium", estimated_time: "30 min"
  },
  {
    brand: "kenmore", appliance: "dryer", error_code: "f03",
    title: "Kenmore Dryer F03 Error Code",
    summary: "Exhaust thermistor open circuit",
    meta_description: "Kenmore dryer F03 exhaust temperature sensor fault. Reseat thermistor at blower housing, vacuum lint from connector.",
    meaning: "F03 means the exhaust thermistor sent an open-circuit reading. The control cannot modulate heat safely without exhaust temperature feedback and may shut off the burner or element.",
    causes: ["Two-wire thermistor connector loose at the blower housing", "Broken wire in the harness near the drum bulkhead", "Failed thermistor element internally open", "Heavy lint shorting the sensor connector"],
    fixes: ["Unplug and reseat the thermistor plug on the blower outlet", "Vacuum lint from the connector area", "Measure thermistor resistance against the service chart at room temperature", "Run a timed cycle on low heat after wiring is verified"],
    when_to_call_technician: "Open thermistor at room temp with intact wiring requires sensor or harness replacement.",
    affected_models: ["Kenmore 110.65132410", "Kenmore 110.67822600", "Kenmore 110.60932990"],
    related_codes: ["f04", "f05", "f01"], difficulty: "medium", estimated_time: "30 min"
  },
  {
    brand: "kenmore", appliance: "dryer", error_code: "f04",
    title: "Kenmore Dryer F04 Error Code",
    summary: "Moisture sensor open",
    meta_description: "Kenmore dryer F04 moisture bar fault. Clean sensor strips inside drum, check wiring to control board.",
    meaning: "F04 indicates the moisture sensor circuit is open. Auto-dry cycles on Kenmore dryers rely on the two metal strips inside the front bulkhead to detect dampness and end the cycle.",
    causes: ["Sensor wire unplugged behind the front panel", "Coating of fabric softener insulating the bars", "Corroded sensor terminals from years of use", "Open circuit in the sensor harness"],
    fixes: ["Clean the two metal moisture bars inside the drum with rubbing alcohol", "Remove front bulkhead access and verify the sensor harness is plugged in", "Inspect for broken wires where the door harness flexes", "Run Sensor Dry on a small damp load as a functional test"],
    when_to_call_technician: "Persistent F04 with clean bars and seated wiring needs moisture sensor harness or board service.",
    affected_models: ["Kenmore 110.65132410", "Kenmore 110.67822600", "Kenmore 110.60932990"],
    related_codes: ["f07", "f03", "f05"], difficulty: "medium", estimated_time: "30 min"
  },
  {
    brand: "kenmore", appliance: "dryer", error_code: "f05",
    title: "Kenmore Dryer F05 Error Code",
    summary: "Door switch circuit open",
    meta_description: "Kenmore dryer F05 door switch fault. Confirm door clicks closed, test switch continuity, replace if drum won't run.",
    meaning: "F05 means the door switch never reported closed. Kenmore dryers block motor and heat circuits until the door strike depresses the switch plunger fully.",
    causes: ["Worn door catch not pressing the switch", "Broken door switch lever", "Door hinge sag misaligning the strike", "Failed door switch internally open"],
    fixes: ["Close the door firmly and listen for the drum light to extinguish", "Inspect the switch plunger through the front panel gap", "Replace the door switch if the drum won't turn with the door fully shut", "Check hinge screws for looseness causing misalignment"],
    when_to_call_technician: "Door switch replacement is a common DIY repair—call service only if wiring inside the door is damaged.",
    affected_models: ["Kenmore 110.65132410", "Kenmore 110.67822600", "Kenmore 110.60932990"],
    related_codes: ["f04", "f03", "f06"], difficulty: "easy", estimated_time: "10 min"
  },
  {
    brand: "kenmore", appliance: "dryer", error_code: "f06",
    title: "Kenmore Dryer F06 Error Code",
    summary: "Communication failure between boards",
    meta_description: "Kenmore dryer F06 UI-to-control comm error. Reseat console harness ribbon, inspect for corrosion.",
    meaning: "F06 means the user interface board and main control lost serial communication. Display, knob input, and heat commands cannot synchronize on Kenmore electronic-console dryers.",
    causes: ["Loose ribbon harness between console and main board", "Power surge damaging communication chips", "Corrosion on the UI connector from laundry humidity", "Failed UI or main control not acknowledging signals"],
    fixes: ["Unplug and remove the console to reseat the UI harness", "Inspect ribbon cable for creases or pin damage", "Power-cycle five minutes after reconnecting", "Test with a basic timed dry cycle"],
    when_to_call_technician: "F06 after reseating both ends of the UI harness usually requires UI board replacement first.",
    affected_models: ["Kenmore 110.65132410", "Kenmore 110.67822600", "Kenmore 110.60932990"],
    related_codes: ["f01", "f02", "f11"], difficulty: "hard", estimated_time: "Call technician"
  },
  {
    brand: "kenmore", appliance: "dryer", error_code: "f07",
    title: "Kenmore Dryer F07 Error Code",
    summary: "Moisture sensor shorted",
    meta_description: "Kenmore dryer F07 shorted moisture sensor. Clean bars, dry harness, replace sensor strip if short persists.",
    meaning: "F07 is the opposite of F04—the moisture sensor circuit reads a short. Auto-dry may end immediately or not advance because the board sees constant wetness.",
    causes: ["Metal debris bridging the two sensor bars", "Water splash on the sensor harness during cleaning", "Shorted wires where harness rubs the cabinet", "Failed sensor strip with internal short"],
    fixes: ["Clean and dry the moisture bars inside the drum", "Inspect the harness behind the bulkhead for pinched insulation", "Disconnect the sensor plug and measure for short to ground", "Run a timed dry instead of auto-dry until repaired"],
    when_to_call_technician: "Sensor circuit tests good but F07 remains with the harness disconnected—replace the sensor assembly.",
    affected_models: ["Kenmore 110.65132410", "Kenmore 110.67822600", "Kenmore 110.60932990"],
    related_codes: ["f04", "f03", "f05"], difficulty: "medium", estimated_time: "30 min"
  },
  {
    brand: "kenmore", appliance: "dryer", error_code: "f08",
    title: "Kenmore Dryer F08 Error Code",
    summary: "Static discharge on the keypad",
    meta_description: "Kenmore dryer F08 static on user interface. Touch Start again after discharge; humidify dry laundry rooms.",
    meaning: "F08 is a static-sensitive keypad fault on Kenmore dryers. Dry winter air or synthetic clothing can discharge into the touch panel and momentarily confuse the UI.",
    causes: ["Very low humidity in the laundry room", "Static buildup from synthetic loads", "Ungrounded outlet missing equipment ground", "Sensitive UI board without discharge protection"],
    fixes: ["Touch a grounded metal surface before pressing dryer buttons", "Unplug one minute and retry the cycle selection", "Avoid dragging feet on carpet before using the console", "Install a humidifier nearby if F08 is frequent in winter"],
    when_to_call_technician: "F08 on every start with a verified grounded outlet may need UI board replacement.",
    affected_models: ["Kenmore 110.65132410", "Kenmore 110.67822600", "Kenmore 110.60932990"],
    related_codes: ["f02", "f11", "f06"], difficulty: "easy", estimated_time: "10 min"
  },
  {
    brand: "kenmore", appliance: "dryer", error_code: "f09",
    title: "Kenmore Dryer F09 Error Code",
    summary: "Software version mismatch",
    meta_description: "Kenmore dryer F09 incompatible software between UI and control. Both boards may need matched replacement pair.",
    meaning: "F09 appears when the user interface and main control report mismatched software versions. After a partial board replacement the two assemblies may not communicate correctly.",
    causes: ["UI board replaced without matching main control revision", "Main control replaced with incompatible firmware level", "Factory flash corruption on one board", "Aftermarket control not paired to the console"],
    fixes: ["Record model and serial numbers from the rating plate", "Verify both boards carry the same engineering revision suffix", "Power-cycle after any single-board swap", "Contact Sears PartsDirect with the serial to order a matched pair"],
    when_to_call_technician: "F09 after replacing either board usually requires installing the manufacturer-matched UI and control set together.",
    affected_models: ["Kenmore 110.65132410", "Kenmore 110.67822600", "Kenmore 110.60932990"],
    related_codes: ["f06", "f01", "f13"], difficulty: "hard", estimated_time: "Call technician"
  },
  {
    brand: "kenmore", appliance: "dryer", error_code: "f10",
    title: "Kenmore Dryer F10 Error Code",
    summary: "Supply voltage out of range",
    meta_description: "Kenmore dryer F10 power supply fault. Test outlet for 120V, check breaker and cord terminal block.",
    meaning: "F10 means the control detected line voltage outside the safe 108–132 VAC window. Motor and heat outputs are disabled to protect components.",
    causes: ["Loose cord at the terminal block", "Shared circuit with heavy loads causing voltage sag", "Tripped or weak breaker contact", "Incorrect outlet wiring with lost neutral"],
    fixes: ["Test the outlet with a multimeter under load", "Tighten the power cord strain relief and terminal screws", "Move the dryer to a dedicated 20-amp laundry circuit if possible", "Reset the breaker fully off then on"],
    when_to_call_technician: "Voltage below 108 VAC at the terminal block with a good outlet indicates house wiring service, not the dryer.",
    affected_models: ["Kenmore 110.65132410", "Kenmore 110.67822600", "Kenmore 110.60932990"],
    related_codes: ["f01", "f11", "f06"], difficulty: "easy", estimated_time: "10 min"
  },
  {
    brand: "kenmore", appliance: "dryer", error_code: "f11",
    title: "Kenmore Dryer F11 Error Code",
    summary: "Motor relay stuck on the control board",
    meta_description: "Kenmore dryer F11 motor relay fault. Unplug immediately if drum runs with door open, replace main control.",
    meaning: "F11 means the main control detected a motor relay that would not release. The drum may continue turning when the cycle should be paused—a safety concern on Kenmore electronic dryers.",
    causes: ["Welded motor relay contacts on the control board", "Shorted motor winding keeping relay energized", "Failed relay driver transistor", "Moisture bridging relay pins on the board"],
    fixes: ["Unplug the dryer immediately if the drum runs with the door open", "Inspect the motor relay area on the control for heat discoloration", "Test motor winding resistance for shorts to ground", "Do not use the dryer until F11 is cleared"],
    when_to_call_technician: "F11 with a good motor requires main control board replacement—relay repair is not practical in the field.",
    affected_models: ["Kenmore 110.65132410", "Kenmore 110.67822600", "Kenmore 110.60932990"],
    related_codes: ["f01", "f06", "f12"], difficulty: "hard", estimated_time: "Call technician"
  },
  {
    brand: "kenmore", appliance: "dryer", error_code: "f12",
    title: "Kenmore Dryer F12 Error Code",
    summary: "Gas valve circuit fault",
    meta_description: "Kenmore gas dryer F12 valve fault. Check gas supply, test valve coils, inspect radiant sensor on burner.",
    meaning: "F12 on Kenmore gas dryers means the gas valve circuit did not respond correctly. The burner will not ignite and clothes remain wet after a full cycle.",
    causes: ["Gas supply valve behind the dryer turned off", "Failed gas valve coil not opening on heat call", "Open radiant flame sensor circuit", "Loose wire at the gas valve harness"],
    fixes: ["Confirm the gas shutoff behind the dryer is fully open", "Listen for valve coil click at heat start—silence means test coils", "Inspect the radiant sensor for soot coating", "Verify other gas appliances in the home work"],
    when_to_call_technician: "Gas valve and burner service requires a qualified technician—do not disassemble gas lines yourself.",
    affected_models: ["Kenmore 110.65132410", "Kenmore 110.67822600", "Kenmore 110.60932990"],
    related_codes: ["f03", "f13", "f01"], difficulty: "hard", estimated_time: "Call technician"
  },
  {
    brand: "kenmore", appliance: "dryer", error_code: "f13",
    title: "Kenmore Dryer F13 Error Code",
    summary: "Lint screen moisture sensor fault",
    meta_description: "Kenmore dryer F13 lint screen sensor fault. Clean screen housing contacts, reseat harness at console.",
    meaning: "F13 on select Kenmore dryers means the lint screen presence sensor circuit failed. Some models use this input to verify the lint filter is installed before heat is enabled.",
    causes: ["Lint packed around the screen housing contacts", "Screen not fully seated in the channel", "Broken sensor wire at the filter housing", "Failed microswitch in the lint screen pocket"],
    fixes: ["Remove and wash the lint screen—vacuum the housing channel", "Confirm the screen drops fully into place with an audible seat", "Inspect the two contact strips in the housing for corrosion", "Reseat the sensor harness behind the console"],
    when_to_call_technician: "F13 with a clean, seated screen and good contacts needs the lint housing sensor or harness replaced.",
    affected_models: ["Kenmore 110.65132410", "Kenmore 110.67822600", "Kenmore 110.60932990"],
    related_codes: ["f04", "f07", "f01"], difficulty: "easy", estimated_time: "15 min"
  },
  {
    brand: "kenmore", appliance: "dryer", error_code: "f14",
    title: "Kenmore Dryer F14 Error Code",
    summary: "Heating element relay stuck",
    meta_description: "Kenmore electric dryer F14 heat relay fault. Unplug if heat runs continuously, test element, replace control board.",
    meaning: "F14 means the main control detected a heating element relay that would not open. The dryer may overheat or continue heating when the cycle should be in cool-down.",
    causes: ["Welded heat relay on the electronic control", "Shorted heating element leaking to ground", "Failed relay driver on the board", "Loose element wire causing erratic current draw"],
    fixes: ["Unplug immediately if the drum is hot with no cycle running", "Measure element resistance and check for ground leakage", "Inspect the control board relay area for burn marks", "Do not run heated cycles until F14 is diagnosed"],
    when_to_call_technician: "Good element with persistent F14 requires main control board replacement.",
    affected_models: ["Kenmore 110.65132410", "Kenmore 110.67822600", "Kenmore 110.60932990"],
    related_codes: ["f01", "f11", "f03"], difficulty: "hard", estimated_time: "Call technician"
  },
  {
    brand: "kenmore", appliance: "dryer", error_code: "f15",
    title: "Kenmore Dryer F15 Error Code",
    summary: "Thermistor short circuit",
    meta_description: "Kenmore dryer F15 shorted exhaust thermistor. Inspect blower housing wiring, replace thermistor if shorted.",
    meaning: "F15 means the exhaust thermistor reads a short circuit. The control disables heat because it cannot trust exhaust temperature feedback.",
    causes: ["Thermistor wires pinched at the blower housing", "Water from a vent leak shorting the connector", "Failed thermistor with internal short", "Metal screw through harness insulation"],
    fixes: ["Unplug and inspect thermistor wiring along the blower outlet", "Dry the connector if moisture is present", "Measure resistance—near zero ohms at room temp confirms a short", "Replace the thermistor if wiring is intact"],
    when_to_call_technician: "New thermistor with immediate F15 may indicate a control board input fault.",
    affected_models: ["Kenmore 110.65132410", "Kenmore 110.67822600", "Kenmore 110.60932990"],
    related_codes: ["f03", "f14", "f01"], difficulty: "medium", estimated_time: "30 min"
  }
];
