/** Researched unique copy — Kenmore oven F03–F17. Sources: Kenmore 790.x range service manual, Frigidaire ERC fault codes */
export default [
  {
    brand: "kenmore", appliance: "oven", error_code: "f03",
    title: "Kenmore Oven F03 Error Code",
    summary: "Open oven temperature sensor",
    meta_description: "Kenmore oven F03 RTD sensor open. Check probe connector behind range, measure resistance at room temp.",
    meaning: "F03 on Kenmore 790-series ranges means the oven temperature sensor (RTD) circuit is open. The electronic range control cannot regulate bake or broil without a valid probe signal.",
    causes: ["Sensor plug loose behind the rear panel", "Broken sensor wire inside the oven cavity routing", "Failed RTD probe internally open", "Connector corrosion from steam at the broil element"],
    fixes: ["Shut off power at the breaker", "Remove the rear lower panel and reseat the sensor harness", "Measure probe resistance—about 1080 ohms at room temperature on many models", "Replace the probe if resistance reads infinite"],
    when_to_call_technician: "New probe with correct ohms but persistent F03 indicates ERC wiring service.",
    affected_models: ["Kenmore Elite 790.75903", "Kenmore 790.46187300", "Kenmore 790.72409410"],
    related_codes: ["f04", "f05", "f06"], difficulty: "medium", estimated_time: "30 min"
  },
  {
    brand: "kenmore", appliance: "oven", error_code: "f04",
    title: "Kenmore Oven F04 Error Code",
    summary: "Shorted oven temperature sensor",
    meta_description: "Kenmore F04 shorted oven sensor. Inspect probe for bare wire touching cavity, replace RTD if shorted.",
    meaning: "F04 means the oven temperature sensor reads a short circuit. The ERC disables heat to prevent uncontrolled temperature rise.",
    causes: ["Sensor wire pinched against the oven liner", "Moisture shorting the connector after steam cleaning", "Failed probe with internal short", "Metal braid touching terminal screws"],
    fixes: ["Disconnect power and inspect the sensor wire route through the cavity", "Dry the connector thoroughly if wet", "Measure resistance—near zero ohms indicates a shorted probe", "Install a new probe matched to your Kenmore model number"],
    when_to_call_technician: "F04 with a disconnected probe means a harness short—trace wiring to the ERC.",
    affected_models: ["Kenmore Elite 790.75903", "Kenmore 790.46187300", "Kenmore 790.72409410"],
    related_codes: ["f03", "f05", "f06"], difficulty: "medium", estimated_time: "30 min"
  },
  {
    brand: "kenmore", appliance: "oven", error_code: "f05",
    title: "Kenmore Oven F05 Error Code",
    summary: "Oven door latch motor fault",
    meta_description: "Kenmore F05 door lock error on self-clean models. Check latch motor, wiring, and door alignment.",
    meaning: "F05 appears on self-cleaning Kenmore ovens when the door latch cannot lock or unlock on command. Clean and convection cycles may be blocked until the latch reports correct position.",
    causes: ["Food debris on the latch hook preventing engagement", "Failed latch motor actuator", "Warped door hinge misaligning the strike", "Broken wire in the door switch harness"],
    fixes: ["Cancel any active clean cycle and allow the oven to cool", "Inspect the latch slot on the door frame for grease buildup", "Listen for latch motor movement when selecting self-clean", "Verify the door closes flush against the gasket"],
    when_to_call_technician: "Latch motor with no movement after cleaning needs model-specific latch assembly replacement.",
    affected_models: ["Kenmore Elite 790.75903", "Kenmore 790.46187300", "Kenmore 790.72409410"],
    related_codes: ["f06", "f07", "f03"], difficulty: "medium", estimated_time: "30 min"
  },
  {
    brand: "kenmore", appliance: "oven", error_code: "f06",
    title: "Kenmore Oven F06 Error Code",
    summary: "Door lock switch circuit fault",
    meta_description: "Kenmore F06 door switch error. Test latch switches, verify lock engages before clean cycle.",
    meaning: "F06 means the door lock switch circuit failed verification. The ERC detected an unexpected open or short in the lock position feedback.",
    causes: ["Latch switch stuck from carbon after clean cycles", "Switch harness unplugged during prior service", "Failed dual-switch latch assembly", "ERC not reading switch bounce correctly"],
    fixes: ["Power off and manually move the latch to feel for binding", "Inspect the two microswitches on the latch motor", "Reseat the latch harness at the ERC", "Run a short bake at 350°F before attempting self-clean again"],
    when_to_call_technician: "Replace the door latch assembly when switches test bad or latch motor stalls.",
    affected_models: ["Kenmore Elite 790.75903", "Kenmore 790.46187300", "Kenmore 790.72409410"],
    related_codes: ["f05", "f07", "f08"], difficulty: "medium", estimated_time: "30 min"
  },
  {
    brand: "kenmore", appliance: "oven", error_code: "f07",
    title: "Kenmore Oven F07 Error Code",
    summary: "Lock motor circuit failure",
    meta_description: "Kenmore F07 lock motor fault. No latch movement on self-clean—replace door lock motor assembly.",
    meaning: "F07 specifically targets the lock motor output circuit. The ERC commanded latch movement but did not detect motor response.",
    causes: ["Burned lock motor windings", "Relay on ERC not sending voltage to motor", "Mechanical jam in latch linkage", "Broken motor gear inside the latch"],
    fixes: ["Disconnect power before inspecting the latch motor", "Check for 120 VAC at the motor during lock command in service mode", "Lubricate only per service manual—excess grease attracts dust", "Replace latch assembly if motor is open or seized"],
    when_to_call_technician: "Voltage at motor with no shaft rotation confirms latch motor replacement.",
    affected_models: ["Kenmore Elite 790.75903", "Kenmore 790.46187300", "Kenmore 790.72409410"],
    related_codes: ["f05", "f06", "f09"], difficulty: "hard", estimated_time: "Call technician"
  },
  {
    brand: "kenmore", appliance: "oven", error_code: "f08",
    title: "Kenmore Oven F08 Error Code",
    summary: "Cooling fan circuit fault",
    meta_description: "Kenmore F08 cooling fan error. Fan should run during bake—check harness and fan motor.",
    meaning: "F08 means the oven cooling fan did not start when required. Electronic controls and door components depend on airflow during heat operation on Kenmore wall ovens.",
    causes: ["Fan blade obstructed by wiring tie", "Open fan motor winding", "Loose connector at the rear cooling fan", "ERC fan relay failed"],
    fixes: ["Shut off power and spin the cooling fan blade by hand", "Remove the rear panel and reseat the fan harness", "Listen for fan start within a minute of turning oven on", "Clear any foil or storage against rear vents"],
    when_to_call_technician: "Fan motor that won't run with good voltage needs cooling fan replacement.",
    affected_models: ["Kenmore Elite 790.75903", "Kenmore 790.46187300", "Kenmore 790.72409410"],
    related_codes: ["f09", "f10", "f06"], difficulty: "medium", estimated_time: "30 min"
  },
  {
    brand: "kenmore", appliance: "oven", error_code: "f09",
    title: "Kenmore Oven F09 Error Code",
    summary: "Oven exceeds maximum temperature",
    meta_description: "Kenmore F09 over-temperature fault. Shut off breaker, test sensor and ERC—do not use until cleared.",
    meaning: "F09 is a safety over-temperature fault. The ERC detected oven temperature above the safe limit—often from a welded relay or failed sensor reading low.",
    causes: ["Bake relay stuck closed on the ERC", "Sensor detached giving false cold reading", "Runaway clean cycle with latch fault", "External heat source too close to the range"],
    fixes: ["Turn off the breaker immediately and leave the door closed until cool", "Inspect the sensor mounting in the upper oven cavity", "Do not restart until F09 cause is identified", "Test bake element for continuity to ground when power is off"],
    when_to_call_technician: "F09 after cooldown with a good sensor strongly suggests ERC relay failure—replace the control board.",
    affected_models: ["Kenmore Elite 790.75903", "Kenmore 790.46187300", "Kenmore 790.72409410"],
    related_codes: ["f03", "f04", "f10"], difficulty: "hard", estimated_time: "Call technician"
  },
  {
    brand: "kenmore", appliance: "oven", error_code: "f10",
    title: "Kenmore Oven F10 Error Code",
    summary: "Runaway temperature or RTD mismatch",
    meta_description: "Kenmore F10 temperature runaway. Power off, test oven sensor and ERC relays before reuse.",
    meaning: "F10 indicates the oven heated without proportional control—similar to F09 on Kenmore 790 platforms. The ERC shuts down all heat outputs.",
    causes: ["Shorted bake element leaking to ground", "ERC bake relay welded shut", "Sensor reading far below actual cavity temp", "Broil element on continuously from relay fault"],
    fixes: ["Disconnect power at the breaker for 30 minutes", "Measure bake element resistance and ground leakage", "Verify the sensor reads rising resistance as the cavity cools", "Replace sensor first if readings are erratic"],
    when_to_call_technician: "Good sensor and element with immediate F10 on preheat needs ERC replacement.",
    affected_models: ["Kenmore Elite 790.75903", "Kenmore 790.46187300", "Kenmore 790.72409410"],
    related_codes: ["f09", "f03", "f11"], difficulty: "hard", estimated_time: "Call technician"
  },
  {
    brand: "kenmore", appliance: "oven", error_code: "f11",
    title: "Kenmore Oven F11 Error Code",
    summary: "Shorted keypad or touch panel",
    meta_description: "Kenmore F11 shorted key fault on oven UI. Dry the panel, replace touchpad if short persists.",
    meaning: "F11 means the oven user interface detected a short on the keypad matrix. Buttons may be unresponsive or trigger randomly.",
    causes: ["Liquid spilled on the control panel", "Steam from cooktop shorting the membrane", "Cracked overlay bridging keys", "Failed ERC keypad input driver"],
    fixes: ["Power off and dry the control area thoroughly", "Avoid cleaning with excessive water on the touch panel", "Unplug ribbon harness at ERC and inspect for corrosion", "Replace touchpad if F11 shows with harness disconnected from UI"],
    when_to_call_technician: "Touchpad or ERC replacement depending on whether short clears with UI unplugged.",
    affected_models: ["Kenmore Elite 790.75903", "Kenmore 790.46187300", "Kenmore 790.72409410"],
    related_codes: ["f12", "f13", "f08"], difficulty: "medium", estimated_time: "30 min"
  },
  {
    brand: "kenmore", appliance: "oven", error_code: "f12",
    title: "Kenmore Oven F12 Error Code",
    summary: "Touch pad key stuck closed",
    meta_description: "Kenmore F12 stuck oven key. Clean panel, power-cycle—replace UI if a key reads pressed constantly.",
    meaning: "F12 is a stuck-key fault distinct from F11 short. One button appears continuously pressed, blocking other inputs on the Kenmore range console.",
    causes: ["Grease under the Start or Cancel pad", "Membrane collapse from age", "Moisture under the overlay from boil-over", "ERC interpreting noise as a held key"],
    fixes: ["Clean around all buttons with a damp cloth then dry", "Press each key several times to free a stuck pad", "Power-cycle at the breaker for two minutes", "Avoid using foil on racks touching the door sensor"],
    when_to_call_technician: "Replace the oven touchpad when F12 appears with a clean dry panel untouched.",
    affected_models: ["Kenmore Elite 790.75903", "Kenmore 790.46187300", "Kenmore 790.72409410"],
    related_codes: ["f11", "f13", "f05"], difficulty: "medium", estimated_time: "30 min"
  },
  {
    brand: "kenmore", appliance: "oven", error_code: "f13",
    title: "Kenmore Oven F13 Error Code",
    summary: "ERC internal memory fault",
    meta_description: "Kenmore F13 EEPROM error on oven control. Unplug five minutes, replace ERC if code returns every start.",
    meaning: "F13 means the electronic range control failed a memory checksum at power-up. Stored calibration and timing tables may be corrupt.",
    causes: ["Power surge on the range circuit", "Moisture on ERC from steam or boil-over", "Age-related EEPROM failure", "Loose logic supply connector"],
    fixes: ["Shut off the breaker for five minutes", "Inspect ERC area for steam damage behind the console", "Reseat all harness plugs into the ERC", "Run a short 350°F bake test after reset"],
    when_to_call_technician: "Immediate F13 on every power-up requires ERC board replacement matched to model suffix.",
    affected_models: ["Kenmore Elite 790.75903", "Kenmore 790.46187300", "Kenmore 790.72409410"],
    related_codes: ["f14", "f15", "f11"], difficulty: "hard", estimated_time: "Call technician"
  },
  {
    brand: "kenmore", appliance: "oven", error_code: "f14",
    title: "Kenmore Oven F14 Error Code",
    summary: "ERC EEPROM data corruption",
    meta_description: "Kenmore F14 control memory data fault. Inspect harness, replace electronic range control.",
    meaning: "F14 is a secondary EEPROM data fault on the Kenmore ERC platform. Cooking functions may be unpredictable until the board is replaced.",
    causes: ["Brownout during self-clean", "Incorrect board substituted in prior repair", "Logic ground loose at ERC mount", "Manufacturing defect in memory chip batch"],
    fixes: ["Verify the installed ERC part number against the tech sheet", "Tighten ERC mounting screws for good ground", "Avoid running self-clean until fault clears", "Document serial number for Sears PartsDirect ordering"],
    when_to_call_technician: "Persistent F14 after one reset requires a new ERC from Kenmore parts.",
    affected_models: ["Kenmore Elite 790.75903", "Kenmore 790.46187300", "Kenmore 790.72409410"],
    related_codes: ["f13", "f15", "f16"], difficulty: "hard", estimated_time: "Call technician"
  },
  {
    brand: "kenmore", appliance: "oven", error_code: "f15",
    title: "Kenmore Oven F15 Error Code",
    summary: "ERC processor communication fault",
    meta_description: "Kenmore F15 oven control comm error. Reseat UI ribbon to ERC, replace board if fault persists.",
    meaning: "F15 indicates internal communication failure within the ERC or between ERC and the touch UI. Display may freeze or show garbage characters.",
    causes: ["Loose ribbon cable between touchpad and ERC", "Failed ERC microcontroller", "Static discharge damaging comm lines", "UI and ERC revision mismatch after repair"],
    fixes: ["Power off and reseat the UI ribbon at both ends", "Inspect for burnt pins on the ERC header", "Match replacement boards to the exact model revision", "Test bake operation after reseat"],
    when_to_call_technician: "F15 with verified harness needs ERC or touchpad replacement as a matched set.",
    affected_models: ["Kenmore Elite 790.75903", "Kenmore 790.46187300", "Kenmore 790.72409410"],
    related_codes: ["f13", "f14", "f16"], difficulty: "hard", estimated_time: "Call technician"
  },
  {
    brand: "kenmore", appliance: "oven", error_code: "f16",
    title: "Kenmore Oven F16 Error Code",
    summary: "Communication error between ERC and UI",
    meta_description: "Kenmore F16 UI-to-ERC link fault. Check ribbon cable, replace touch panel or control board.",
    meaning: "F16 specifically flags lost serial communication between the display UI and the ERC—common after replacing only one of the two assemblies on Kenmore ranges.",
    causes: ["Partial board replacement with incompatible firmware", "Cut ribbon cable during console removal", "Corrosion on low-voltage comm pins", "Failed ERC UART output driver"],
    fixes: ["Compare part numbers on UI and ERC before mixing boards", "Replace the ribbon if creased or torn", "Run a keypad test through service mode if available", "Power-cycle after any harness work"],
    when_to_call_technician: "Order UI and ERC together using model and serial when F16 follows a single-board swap.",
    affected_models: ["Kenmore Elite 790.75903", "Kenmore 790.46187300", "Kenmore 790.72409410"],
    related_codes: ["f15", "f11", "f13"], difficulty: "hard", estimated_time: "Call technician"
  },
  {
    brand: "kenmore", appliance: "oven", error_code: "f17",
    title: "Kenmore Oven F17 Error Code",
    summary: "Probe or meat thermometer circuit fault",
    meta_description: "Kenmore F17 temperature probe jack error. Check built-in probe connection, jack wiring to ERC.",
    meaning: "F17 appears on Kenmore models with a temperature probe jack. The ERC detected an open or short in the external meat probe circuit during convection roast or probe bake.",
    causes: ["Probe not fully seated in the jack", "Damaged probe cable from kinking", "Jack wiring loose at the ERC", "Probe tip damaged from high heat exposure"],
    fixes: ["Insert the probe firmly until it clicks", "Test with a known-good Kenmore probe if available", "Inspect the jack behind the console for loose wires", "Cancel probe mode and use timed bake as a workaround"],
    when_to_call_technician: "Good probe with F17 at the jack needs receptacle or ERC input circuit repair.",
    affected_models: ["Kenmore Elite 790.75903", "Kenmore 790.46187300", "Kenmore 790.72409410"],
    related_codes: ["f03", "f04", "f09"], difficulty: "medium", estimated_time: "30 min"
  }
];
