/** Researched unique copy — LG oven/range codes. Sources: LG Error Codes, Register Appliance, iFixit */
export default [
  {
    brand: "lg", appliance: "oven", error_code: "f9",
    title: "LG Oven F9 Error Code",
    summary: "Oven failed to heat above 150°F in 5 minutes",
    meta_description: "LG F9 means no heat during preheat. Reset breaker; on gas check igniter glow, on electric test bake element and sensor.",
    meaning: "F9 triggers when the oven cannot exceed 150°F within five minutes of preheat with the door closed. LG shuts heat as a safety response—common on both gas and electric ranges but the failed part differs by fuel type.",
    causes: ["Weak gas igniter glowing but not opening valve", "Open bake or broil element on electric models", "Temperature sensor reading ~1080Ω out of spec at room temp", "Failed relay on main oven control board"],
    fixes: ["Press CLEAR/OFF, then turn the range breaker OFF five minutes", "Retry Bake at 350°F and watch for igniter glow (gas) or element orange heat (electric)", "Confirm household gas valve is open on gas ranges", "Stop using the oven if F9 returns immediately after reset"],
    when_to_call_technician: "Schedule service for igniter, element, sensor, or relay board testing—F9 rarely clears without part replacement.",
    affected_models: ["LG LRG4113ST", "LG LREL6325F", "LG LDG4313ST"],
    related_codes: ["f19", "f11", "f3"], difficulty: "medium", estimated_time: "30 min"
  },
  {
    brand: "lg", appliance: "oven", error_code: "f11",
    title: "LG Oven F11 Error Code",
    summary: "Communication error between oven PCBs",
    meta_description: "LG F11 means cooktop and oven boards lost communication over 10 seconds. Reset power; check ribbon cables if F11 persists.",
    meaning: "F11 is a Communication Error between the cooktop PCB and oven PCB—often seen during self-clean when both boards must coordinate door lock and heat. The display may freeze or cancel clean mode.",
    causes: ["Loose ribbon cable between UI and oven board", "Power surge during self-clean high heat", "Moisture on connectors after steam clean", "Failed oven or cooktop sub-PCB"],
    fixes: ["Turn breaker OFF ten to thirty minutes per LG service bulletins", "Avoid starting self-clean until F11 clears", "Ensure the range cord is fully seated at the junction box", "Note whether F11 appears only in self-clean or all modes"],
    when_to_call_technician: "Persistent F11 after cable inspection requires PCB replacement—model-matched boards only.",
    affected_models: ["LG LREL6325F", "LG LRG4115ST", "LG LDE4413ST"],
    related_codes: ["f9", "f19", "f16"], difficulty: "hard", estimated_time: "Call technician"
  },
  {
    brand: "lg", appliance: "oven", error_code: "f19",
    title: "LG Oven F19 Error Code",
    summary: "Extended no-heat fault during preheat",
    meta_description: "LG F19 is a stricter heating fault than F9—temp stayed below thresholds during preheat. Check igniter, elements, and door seal.",
    meaning: "F19 covers oven no-heat cases where temperature failed to rise at least 10°F above starting temp within five minutes, or stayed at or below 100°F during preheat—excluding proof and warm modes on many firmware versions.",
    causes: ["Same root failures as F9 but more sensitive timing thresholds", "Door not fully latched letting heat escape", "Failed cooling fan not moving air in convection models", "Thermal fuse opened after prior overheating"],
    fixes: ["Verify the oven door closes flush—no rack sticking out", "Run standard Bake, not convection, for the first test after reset", "Breaker reset five minutes before retry", "Listen for convection fan at preheat start on fan-assisted models"],
    when_to_call_technician: "F19 with verified door closure needs heating circuit diagnosis identical to F9 service path.",
    affected_models: ["LG LREL6325F", "LG LRG4113ST", "LG LDG4315ST"],
    related_codes: ["f9", "f11", "f3"], difficulty: "medium", estimated_time: "30 min"
  },
  {
    brand: "lg", appliance: "oven", error_code: "f3",
    title: "LG Oven F3 Error Code",
    summary: "Oven temperature sensor shorted",
    meta_description: "LG F3 means shorted oven temperature sensor. Unplug range and test sensor ohms—replace if near zero.",
    meaning: "F3 indicates the oven temperature sensor circuit reads shorted to ground. The board sees invalid low resistance and disables heat to prevent runaway temperature.",
    causes: ["Sensor wire pinched against oven cavity metal", "Shorted RTD probe from grease fire damage", "Moisture bridge after steam cleaning before dry-out", "Harness chafe at the door hinge area"],
    fixes: ["Turn off breaker before touching sensor wires", "Disconnect sensor at the board and measure ohms—should be ~1080Ω at room temperature, not near zero", "Inspect harness along the upper oven cavity", "Allow 24 hours dry time if steam moisture triggered F3 once"],
    when_to_call_technician: "Replace sensor and harness if short persists with sensor unplugged from the probe side.",
    affected_models: ["LG LRG4113ST", "LG LREL6325F", "LG LDG4313ST"],
    related_codes: ["f4", "f9", "f19"], difficulty: "medium", estimated_time: "30 min"
  },
  {
    brand: "lg", appliance: "oven", error_code: "f4",
    title: "LG Oven F4 Error Code",
    summary: "Oven temperature sensor open circuit",
    meta_description: "LG F4 means open oven sensor circuit. Check connector CN31 pins 4–5 for ~1.09kΩ at 25°C.",
    meaning: "F4 is the open-circuit counterpart to F3—the temperature sensor or its wiring reads infinite resistance, so the control cannot detect oven temperature.",
    causes: ["Sensor connector CN31 loose at main PCB", "Broken sensor wire inside the oven cavity insulation", "Failed RTD element internally open", "Previous repair left sensor unplugged"],
    fixes: ["Power off and reseat CN31 at the main board", "Measure sensor at the probe: open reading confirms replacement needed", "Compare with LG spec chart printed on service manual for your model year", "Retry preheat after reseat if ohms were borderline"],
    when_to_call_technician: "Open sensor with intact wiring requires probe replacement—access from inside the oven rear wall.",
    affected_models: ["LG LRG4115ST", "LG LREL6325F", "LG LDG4315ST"],
    related_codes: ["f3", "f9", "f5"], difficulty: "medium", estimated_time: "30 min"
  },
  {
    brand: "lg", appliance: "oven", error_code: "f5",
    title: "LG Oven F5 Error Code",
    summary: "Oven door lock circuit fault",
    meta_description: "LG F5 relates to door lock motor or switch during clean or bake. Confirm door fully closed; service lock assembly if F5 persists.",
    meaning: "F5 reports a door Lock circuit fault—the lock motor did not reach the expected position during self-clean or the lock switch feedback failed during normal bake on some models.",
    causes: ["Food soil preventing lock hook engagement", "Failed door lock motor actuator", "Broken lock switch", "Warped door hinge misaligning the latch"],
    fixes: ["Allow the oven to cool completely before opening if locked", "Clean latch receiver on the frame after cool-down", "Power-cycle after cooling—never force the door during F5", "Run a standard Bake test before retrying self-clean"],
    when_to_call_technician: "Door lock motor replacement is required if F5 appears every self-clean attempt with a clean latch area.",
    affected_models: ["LG LREL6325F", "LG LRG4113ST", "LG LDG4313ST"],
    related_codes: ["f6", "f11", "f9"], difficulty: "hard", estimated_time: "Call technician"
  },
  {
    brand: "lg", appliance: "oven", error_code: "f6",
    title: "LG Oven F6 Error Code",
    summary: "Oven door lock not releasing",
    meta_description: "LG F6 means door lock stuck locked after cycle. Wait for cooldown; do not force door—service lock motor if needed.",
    meaning: "F6 indicates the door Lock will not unlock after the clean or bake cycle finished—often the lock motor or switch stuck in the locked position while the oven is still hot.",
    causes: ["Normal hot lockout still within cooldown window", "Failed lock motor cannot retract hook", "Broken lock linkage after self-clean overheating", "Control board not sending unlock command"],
    fixes: ["Wait 30–60 minutes for automatic unlock as oven cools", "Turn breaker off only after confirming oven is off and cooling—never mid-flame on gas", "Do not pry the door—risk shattering glass", "Once cool and unlocked, inspect latch for bent hook"],
    when_to_call_technician: "If the door stays locked cold for over two hours, emergency service is needed to avoid being trapped shut.",
    affected_models: ["LG LREL6325F", "LG LRG4115ST", "LG LDG4315ST"],
    related_codes: ["f5", "f11", "f16"], difficulty: "hard", estimated_time: "Call technician"
  },
  {
    brand: "lg", appliance: "oven", error_code: "f7",
    title: "LG Oven F7 Error Code",
    summary: "Touch panel or key stuck",
    meta_description: "LG F7 means a keypad is sensed pressed. Dry the glass, release stuck keys, power-cycle the UI.",
    meaning: "F7 is a Function or key Fault—the touch panel reports a button held continuously. Oven may refuse to start bake or broil until the panel state clears.",
    causes: ["Liquid on touch glass after cleaning", "Physical object leaning on the panel", "Failed touch membrane behind the glass", "Control board key input shorted"],
    fixes: ["Dry the panel thoroughly and leave unused ten minutes", "Press each soft key once to release contact", "Turn breaker off five minutes", "Avoid abrasive cleaners that scratch touch surfaces"],
    when_to_call_technician: "F7 at idle with dry glass indicates UI board replacement.",
    affected_models: ["LG LREL6325F", "LG LRG4113ST", "LG LDG4313ST"],
    related_codes: ["f8", "f11", "f16"], difficulty: "easy", estimated_time: "10 min"
  },
  {
    brand: "lg", appliance: "oven", error_code: "f8",
    title: "LG Oven F8 Error Code",
    summary: "Cooling fan for control board fault",
    meta_description: "LG F8 means the oven control cooling fan failed. Oven may shut down to protect electronics—fan or board service needed.",
    meaning: "F8 indicates the cooling fan that protects the oven control board did not spin when commanded—common after self-clean high ambient temperatures inside the console.",
    causes: ["Fan blade blocked by grease dust behind the panel", "Failed cooling fan motor", "Fan harness melted near the oven top", "Board not sending fan voltage after surge"],
    fixes: ["Allow oven to cool completely with breaker off", "Listen for a small fan when starting bake—silence suggests F8 cause", "Avoid covering vent slots on the backguard", "Retry after cooldown before assuming fan motor failure"],
    when_to_call_technician: "Replace cooling fan assembly if no spin with verified 120V at fan plug during service mode.",
    affected_models: ["LG LRG4115ST", "LG LREL6325F", "LG LDG4315ST"],
    related_codes: ["f11", "f16", "f9"], difficulty: "hard", estimated_time: "Call technician"
  },
  {
    brand: "lg", appliance: "oven", error_code: "f10",
    title: "LG Oven F10 Error Code",
    summary: "Runaway temperature detected",
    meta_description: "LG F10 means oven overheated beyond safe limit. Turn off breaker immediately; inspect sensor and relay board.",
    meaning: "F10 is an over-temperature fault—the board detected oven temperature climbing beyond safe limits, often from a welded relay, shorted sensor, or stuck heat command during clean.",
    causes: ["Relay stuck closed powering bake element continuously", "Shorted temperature sensor telling board oven is cold", "Failed cooling fan during broil", "User cancelled clean late leaving elements energized abnormally"],
    fixes: ["Turn OFF breaker immediately when F10 appears with smell or smoke", "Do not restart until the oven cools to room temperature", "Inspect bake element for blistering or ground faults", "Schedule service before next use—F10 is a serious safety flag"],
    when_to_call_technician: "Mandatory service after F10—relay board or sensor testing required before operating again.",
    affected_models: ["LG LRG4113ST", "LG LREL6325F", "LG LDG4313ST"],
    related_codes: ["f3", "f9", "f8"], difficulty: "hard", estimated_time: "Call technician"
  },
  {
    brand: "lg", appliance: "oven", error_code: "f12",
    title: "LG Oven F12 Error Code",
    summary: "Touch panel communication fault",
    meta_description: "LG F12 indicates display PCB communication error. Reset breaker; inspect ribbon cable to touch panel.",
    meaning: "F12 is a touch panel Communication fault distinct from F11—the link between the glass UI and the oven processor failed, freezing buttons or showing garbled temps.",
    causes: ["Ribbon cable unseated at the display", "Steam from cooktop penetrating the UI flex", "Failed display PCB", "ESD damage after improper board handling"],
    fixes: ["Power off five minutes at breaker", "Dry the control area if steam cleaning occurred recently", "Tap buttons gently after power return—avoid hammering glass", "Photograph display behavior for the technician"],
    when_to_call_technician: "F12 every power-on needs display assembly or main board replacement.",
    affected_models: ["LG LREL6325F", "LG LRG4115ST", "LG LDG4315ST"],
    related_codes: ["f11", "f7", "f16"], difficulty: "hard", estimated_time: "Call technician"
  },
  {
    brand: "lg", appliance: "oven", error_code: "f13",
    title: "LG Oven F13 Error Code",
    summary: "Internal temperature mismatch",
    meta_description: "LG F13 means oven sensors disagree on temperature. Often sensor or harness fault—service recommended.",
    meaning: "F13 indicates mismatched temperature readings between sensors or between sensor and expected rate of rise—used on dual-sensor convection models when probes disagree beyond tolerance.",
    causes: ["Secondary convection sensor failed", "Primary sensor drifting high vs secondary", "Harness swap during repair connecting wrong probe", "Board algorithm fault after firmware glitch"],
    fixes: ["Run standard Bake without convection to see if F13 is convection-only", "Breaker reset five minutes", "Avoid opening door repeatedly during preheat when testing", "Record whether F13 appears at start or mid-cycle"],
    when_to_call_technician: "Dual-sensor models need professional comparison of both probes against LG charts.",
    affected_models: ["LG LREL6325F", "LG LRG4115ST", "LG LDG4315ST"],
    related_codes: ["f3", "f4", "f9"], difficulty: "hard", estimated_time: "Call technician"
  },
  {
    brand: "lg", appliance: "oven", error_code: "f14",
    title: "LG Oven F14 Error Code",
    summary: "Meat probe circuit fault",
    meta_description: "LG F14 relates to the oven meat probe input. Unplug probe; replace probe if F14 shows without probe inserted.",
    meaning: "F14 reports a fault on the meat probe jack—short, open, or invalid reading while probe mode is selected or the jack is contaminated.",
    causes: ["Probe not fully seated in the jack", "Damaged probe cable with broken conductors", "Greasy jack shorting contacts", "Board probe input failed"],
    fixes: ["Remove the probe completely and cancel probe mode", "Clean the jack with dry cotton swab—no liquid cleaners", "Test with a known-good LG probe if available", "Use standard Bake without probe to confirm oven heats"],
    when_to_call_technician: "F14 with no probe inserted indicates jack or board repair.",
    affected_models: ["LG LRG4115ST", "LG LREL6325F", "LG LDG4315ST"],
    related_codes: ["f3", "f4", "f13"], difficulty: "easy", estimated_time: "10 min"
  },
  {
    brand: "lg", appliance: "oven", error_code: "f15",
    title: "LG Oven F15 Error Code",
    summary: "Broil element circuit fault",
    meta_description: "LG F15 means broil element or its wiring failed. Inspect broil element for breaks; test continuity when cool.",
    meaning: "F15 indicates the broil element circuit did not draw expected current when broil was commanded—open element, bad wire, or relay not closing.",
    causes: ["Open broil element from age or thermal shock", "Burned wire at broil terminal block", "Relay not energizing broil leg", "Element connector loosened during prior service"],
    fixes: ["Turn breaker off and visually inspect top broil element for gaps or blisters", "Wiggle element connectors gently—they should be tight ceramic blocks", "Run Broil test after reset—no orange glow confirms element path fault", "Use Bake only until service if broil is required for recipes"],
    when_to_call_technician: "Element and relay tests with live voltage belong in professional service.",
    affected_models: ["LG LRG4113ST", "LG LREL6325F", "LG LDG4315ST"],
    related_codes: ["f9", "f10", "f16"], difficulty: "medium", estimated_time: "30 min"
  },
  {
    brand: "lg", appliance: "oven", error_code: "f16",
    title: "LG Oven F16 Error Code",
    summary: "Bake element circuit fault",
    meta_description: "LG F16 means bake element circuit failure. Check lower element and wiring—common companion to F9 no-heat codes.",
    meaning: "F16 reports the bake element circuit fault—when bake is selected the board detects no current or no temperature rise attributable to the lower element.",
    causes: ["Open bake element hidden under floor panel", "Thermal fuse in line to bake element blown", "Relay contact burned open on bake leg", "Loose spade connector on element leads"],
    fixes: ["Cool oven completely before inspection", "Remove oven floor panel per manual to view bake element for breaks", "Reset breaker and observe lower element during preheat", "If F16 pairs with F9, prioritize element and sensor service path"],
    when_to_call_technician: "Bake element replacement requires correct wattage part for your cavity size.",
    affected_models: ["LG LRG4113ST", "LG LREL6325F", "LG LDG4313ST"],
    related_codes: ["f9", "f19", "f15"], difficulty: "medium", estimated_time: "30 min"
  },
];
