/** Researched unique copy — Maytag dryer. Sources: Maytag Product Help, Whirlpool dryer service manual */
export default [
  {
    brand: "maytag", appliance: "dryer", error_code: "f01",
    title: "Maytag Dryer F01 Error Code",
    summary: "Main electronic control board failure",
    meta_description: "Maytag dryer F01 means EEPROM error on the main control. Unplug, reseat harnesses, replace board if fault returns.",
    meaning: "F01 on Maytag dryers signals the main control board failed its internal memory check. Heat, motor, and moisture sensing commands stop until the board resets or is replaced.",
    causes: ["Lightning surge through the laundry circuit", "Loose main harness connector after moving the dryer", "Moisture corrosion on the board from a vent leak", "Failed EEPROM on the electronic control assembly"],
    fixes: ["Unplug the dryer for five minutes before restoring power", "Remove the top panel and reseat the large harness into the control board", "Inspect for burnt traces near the line input terminals", "Run a timed dry on air fluff as a board function test"],
    when_to_call_technician: "F01 that returns immediately after power-up requires a new Maytag electronic control matched to your model suffix.",
    affected_models: ["Maytag MEDC465HW", "Maytag MEDB855DC", "Maytag MED6230HW"],
    related_codes: ["f06", "f13", "f14"], difficulty: "hard", estimated_time: "Call technician"
  },
  {
    brand: "maytag", appliance: "dryer", error_code: "f02",
    title: "Maytag Dryer F02 Error Code",
    summary: "Key stuck on the user interface",
    meta_description: "Maytag F02 stuck button on dryer console. Clean the panel, power-cycle, replace UI if keys read pressed constantly.",
    meaning: "F02 means the console detects a keypad or touch button held continuously. The dryer will not start a cycle while it thinks a selection key is pressed.",
    causes: ["Static discharge locking a touch pad trace", "Spilled liquid on the console membrane", "Cracked overlay shorting adjacent pads", "Failed user interface board"],
    fixes: ["Wipe the console dry with a soft cloth", "Unplug two minutes and touch each button once after restart", "Avoid leaning on the console during operation", "Replace the UI if F02 shows with no keys touched"],
    when_to_call_technician: "UI board replacement is straightforward but requires matching the part to your console style—order by model number.",
    affected_models: ["Maytag MEDB855DC", "Maytag MEDC465HW", "Maytag MED6230HW"],
    related_codes: ["f08", "f11", "f06"], difficulty: "medium", estimated_time: "30 min"
  },
  {
    brand: "maytag", appliance: "dryer", error_code: "f03",
    title: "Maytag Dryer F03 Error Code",
    summary: "Exhaust thermistor open circuit",
    meta_description: "Maytag F03 exhaust temperature sensor fault. Check thermistor wiring at the blower housing.",
    meaning: "F03 means the exhaust thermistor sent an open-circuit reading. The control cannot modulate heat safely without exhaust temperature feedback and may shut off the burner or element.",
    causes: ["Two-wire thermistor connector loose at the blower housing", "Broken wire in the harness near the drum bulkhead", "Failed thermistor element internally open", "Heavy lint shorting the sensor connector"],
    fixes: ["Unplug and reseat the thermistor plug on the blower outlet", "Vacuum lint from the connector area", "Measure thermistor resistance against the service chart at room temperature", "Run a timed cycle on low heat after wiring is verified"],
    when_to_call_technician: "Open thermistor at room temp with intact wiring requires sensor or harness replacement.",
    affected_models: ["Maytag MEDB855DC", "Maytag MED6230HW", "Maytag MGDC465HW"],
    related_codes: ["f04", "f05", "f01"], difficulty: "medium", estimated_time: "30 min"
  },
  {
    brand: "maytag", appliance: "dryer", error_code: "f04",
    title: "Maytag Dryer F04 Error Code",
    summary: "Moisture sensor open",
    meta_description: "Maytag F04 moisture sensing bar fault. Clean sensor strips inside drum, check wiring to the board.",
    meaning: "F04 indicates the moisture sensor circuit is open. Auto-dry cycles rely on these metal strips inside the front bulkhead to detect dampness and end the cycle.",
    causes: ["Sensor wire unplugged behind the front panel", "Coating of fabric softener insulating the bars", "Corroded sensor terminals from years of use", "Open circuit in the sensor harness"],
    fixes: ["Clean the two metal moisture bars inside the drum with rubbing alcohol", "Remove front bulkhead access and verify the sensor harness is plugged in", "Inspect for broken wires where the door harness flexes", "Run Sensor Dry on a small damp load as a functional test"],
    when_to_call_technician: "Persistent F04 with clean bars and seated wiring needs moisture sensor harness or board service.",
    affected_models: ["Maytag MEDC465HW", "Maytag MEDB855DC", "Maytag MED6230HW"],
    related_codes: ["f07", "f03", "f05"], difficulty: "medium", estimated_time: "30 min"
  },
  {
    brand: "maytag", appliance: "dryer", error_code: "f05",
    title: "Maytag Dryer F05 Error Code",
    summary: "Door switch circuit open",
    meta_description: "Maytag F05 door switch fault. Confirm door clicks closed, test switch continuity, replace if the drum won't run with door shut.",
    meaning: "F05 means the door switch never reported closed. Maytag dryers block motor and heat circuits until the door strike depresses the switch plunger fully.",
    causes: ["Worn door catch not pressing the switch", "Broken door switch lever", "Door hinge sag misaligning the strike", "Failed door switch internally open"],
    fixes: ["Close the door firmly and listen for the drum light to extinguish", "Inspect the switch plunger through the front panel gap", "Replace the door switch if the drum won't turn with the door fully shut", "Check hinge screws for looseness causing misalignment"],
    when_to_call_technician: "Door switch replacement is a common DIY repair—call service only if wiring to the switch is damaged inside the door.",
    affected_models: ["Maytag MEDC465HW", "Maytag MGDC465HW", "Maytag MED6230HW"],
    related_codes: ["f04", "f03", "f06"], difficulty: "easy", estimated_time: "10 min"
  },
  {
    brand: "maytag", appliance: "dryer", error_code: "f06",
    title: "Maytag Dryer F06 Error Code",
    summary: "Communication failure between boards",
    meta_description: "Maytag F06 UI-to-control communication error. Reseat console harness, inspect for corrosion.",
    meaning: "F06 means the user interface board and main control lost serial communication. Display, knob input, and heat commands cannot synchronize.",
    causes: ["Loose ribbon harness between console and main board", "Power surge damaging communication chips", "Corrosion on the 6-pin UI connector", "Failed UI or main control not acknowledging signals"],
    fixes: ["Unplug and remove the console to reseat the UI harness", "Inspect ribbon cable for creases or pin damage", "Power-cycle five minutes after reconnecting", "Test with a basic timed dry cycle"],
    when_to_call_technician: "F06 after reseating both ends of the UI harness usually requires UI board replacement first.",
    affected_models: ["Maytag MEDB855DC", "Maytag MED6230HW", "Maytag MEDC465HW"],
    related_codes: ["f01", "f02", "f11"], difficulty: "hard", estimated_time: "Call technician"
  },
  {
    brand: "maytag", appliance: "dryer", error_code: "f07",
    title: "Maytag Dryer F07 Error Code",
    summary: "Moisture sensor shorted",
    meta_description: "Maytag F07 shorted moisture sensor. Clean bars, dry the harness, replace sensor strip if short persists.",
    meaning: "F07 is the opposite of F04—the moisture sensor circuit reads a short. Auto-dry may end immediately or not advance because the board sees constant wetness.",
    causes: ["Metal debris bridging the two sensor bars", "Water splash on the sensor harness during cleaning", "Shorted wires where harness rubs the cabinet", "Failed sensor strip with internal short"],
    fixes: ["Clean and dry the moisture bars inside the drum", "Inspect the harness behind the bulkhead for pinched insulation", "Disconnect the sensor plug and measure for short to ground", "Run a timed dry instead of auto-dry until repaired"],
    when_to_call_technician: "Open sensor circuit tests good but F07 remains with the harness disconnected—replace the sensor assembly.",
    affected_models: ["Maytag MEDC465HW", "Maytag MEDB855DC", "Maytag MED6230HW"],
    related_codes: ["f04", "f03", "f05"], difficulty: "medium", estimated_time: "30 min"
  },
  {
    brand: "maytag", appliance: "dryer", error_code: "f08",
    title: "Maytag Dryer F08 Error Code",
    summary: "Static discharge on the keypad",
    meta_description: "Maytag F08 static on user interface. Touch Start again after discharge; add humidity if laundry room is very dry.",
    meaning: "F08 is a static-sensitive keypad fault. Dry winter air or synthetic clothing can discharge into the touch panel and momentarily confuse the UI.",
    causes: ["Very low humidity in the laundry room", "Static buildup from synthetic loads", "Ungrounded outlet missing equipment ground", "Sensitive UI board without discharge protection"],
    fixes: ["Touch a grounded metal surface before pressing dryer buttons", "Unplug one minute and retry the cycle selection", "Avoid dragging feet on carpet before using the console", "Install a humidifier nearby if F08 is frequent in winter"],
    when_to_call_technician: "F08 on every start with a verified grounded outlet may need UI board replacement.",
    affected_models: ["Maytag MEDB855DC", "Maytag MED6230HW", "Maytag MEDC465HW"],
    related_codes: ["f02", "f11", "f06"], difficulty: "easy", estimated_time: "10 min"
  },
  {
    brand: "maytag", appliance: "dryer", error_code: "f09",
    title: "Maytag Dryer F09 Error Code",
    summary: "Software version mismatch",
    meta_description: "Maytag F09 incompatible software between UI and control. Both boards may need matched replacement pair.",
    meaning: "F09 appears when the user interface and main control report mismatched software versions. After a partial board replacement the two assemblies may not communicate correctly.",
    causes: ["UI board replaced without matching main control revision", "Main control replaced with incompatible firmware level", "Factory flash corruption on one board", "Aftermarket control not paired to the console"],
    fixes: ["Record model and serial numbers from the rating plate", "Verify both boards carry the same engineering revision suffix", "Power-cycle after any single-board swap", "Contact Maytag parts with the serial to order a matched pair"],
    when_to_call_technician: "F09 after replacing either board usually requires installing the manufacturer-matched UI and control set together.",
    affected_models: ["Maytag MEDB855DC", "Maytag MED6230HW", "Maytag MEDC465HW"],
    related_codes: ["f06", "f01", "f13"], difficulty: "hard", estimated_time: "Call technician"
  },
  {
    brand: "maytag", appliance: "dryer", error_code: "f10",
    title: "Maytag Dryer F10 Error Code",
    summary: "Supply voltage out of range",
    meta_description: "Maytag F10 power supply fault. Test the outlet for 120V, check breaker and cord terminal block.",
    meaning: "F10 means the control detected line voltage outside the safe 108–132 VAC window. Motor and heat outputs are disabled to protect components.",
    causes: ["Loose cord at the terminal block", "Shared circuit with heavy loads causing voltage sag", "Tripped or weak breaker contact", "Incorrect outlet wiring with lost neutral"],
    fixes: ["Test the outlet with a multimeter under load", "Tighten the power cord strain relief and terminal screws", "Move the dryer to a dedicated 20-amp laundry circuit if possible", "Reset the breaker fully off then on"],
    when_to_call_technician: "Voltage below 108 VAC at the terminal block with a good outlet indicates house wiring service, not the dryer.",
    affected_models: ["Maytag MEDC465HW", "Maytag MGDC465HW", "Maytag MED6230HW"],
    related_codes: ["f01", "f06", "f05"], difficulty: "medium", estimated_time: "30 min"
  },
  {
    brand: "maytag", appliance: "dryer", error_code: "f11",
    title: "Maytag Dryer F11 Error Code",
    summary: "Shorted keypad detected",
    meta_description: "Maytag F11 shorted key on dryer console. Dry the panel, replace UI if a key reads shorted without touch.",
    meaning: "F11 means the UI sees a continuous short on one keypad line—different from F02 stuck key which is a logic state. Liquid spills or board failure are common triggers.",
    causes: ["Water from a nearby sink splashed on the console", "Shorted membrane under the Start pad", "Liquid fabric softener on the touch surface", "Failed UI board with internal short"],
    fixes: ["Power off and dry the console thoroughly for several hours", "Inspect for visible moisture under the plastic overlay", "Unplug and leave the door open to ventilate the control area", "Replace the UI if F11 persists on a dry panel"],
    when_to_call_technician: "UI replacement is the typical fix when drying does not clear F11.",
    affected_models: ["Maytag MEDB855DC", "Maytag MED6230HW", "Maytag MEDC465HW"],
    related_codes: ["f02", "f08", "f06"], difficulty: "medium", estimated_time: "30 min"
  },
  {
    brand: "maytag", appliance: "dryer", error_code: "f12",
    title: "Maytag Dryer F12 Error Code",
    summary: "Relay failure on the main control",
    meta_description: "Maytag F12 bad relay on electronic control. Heat or motor may not energize—board replacement likely.",
    meaning: "F12 indicates a drive relay on the main control failed its self-test. The board cannot reliably switch heat, motor, or valve outputs.",
    causes: ["Relay welded closed from age or surge", "Burnt relay driver transistor on the board", "Moisture intrusion on the relay bank", "Overloaded motor circuit stressing the relay"],
    fixes: ["Unplug five minutes and attempt one timed dry cycle", "Listen for heat or drum start—silence with F12 confirms output failure", "Inspect the board for burnt relay areas near heat outputs", "Note model number before ordering the control assembly"],
    when_to_call_technician: "F12 almost always requires main electronic control replacement—relays are not field-serviceable.",
    affected_models: ["Maytag MEDB855DC", "Maytag MED6230HW", "Maytag MGDC465HW"],
    related_codes: ["f01", "f06", "f10"], difficulty: "hard", estimated_time: "Call technician"
  },
  {
    brand: "maytag", appliance: "dryer", error_code: "f13",
    title: "Maytag Dryer F13 Error Code",
    summary: "EEPROM checksum error on control",
    meta_description: "Maytag F13 control memory checksum fault. Power-cycle; replace main board if code returns every start.",
    meaning: "F13 means the main control EEPROM failed a checksum verification at power-up. Stored cycle profiles and calibration data may be corrupt.",
    causes: ["Brownout during a previous cycle", "Incomplete power loss leaving memory half-written", "Age-related EEPROM degradation", "Static discharge at the board connector"],
    fixes: ["Unplug for ten minutes to allow full capacitor discharge", "Reseat the main harness at the control board", "Avoid using extension cords that cause voltage dips", "Run one short air-fluff cycle after reset"],
    when_to_call_technician: "Recurring F13 at every power-up requires a new main control—memory cannot be reflashed in the field.",
    affected_models: ["Maytag MEDC465HW", "Maytag MEDB855DC", "Maytag MED6230HW"],
    related_codes: ["f01", "f14", "f15"], difficulty: "hard", estimated_time: "Call technician"
  },
  {
    brand: "maytag", appliance: "dryer", error_code: "f14",
    title: "Maytag Dryer F14 Error Code",
    summary: "Secondary EEPROM verification failed",
    meta_description: "Maytag F14 alternate memory fault on dryer control. Treat like F13—inspect harness, replace board.",
    meaning: "F14 is a second checksum fault path on the same control platform as F13. The board detected corrupted non-volatile memory during initialization.",
    causes: ["Power surge through the neutral leg", "Water drip on the board from a roof leak above", "Connector intermittently losing 5V logic supply", "Manufacturing defect in a batch EEPROM"],
    fixes: ["Verify the dryer cord and outlet ground are intact", "Inspect the control area for water stains or pest damage", "Reseat all multi-pin connectors on the board", "Document the code and serial for warranty if applicable"],
    when_to_call_technician: "F14 that survives a harness reseat needs electronic control replacement.",
    affected_models: ["Maytag MEDB855DC", "Maytag MED6230HW", "Maytag MEDC465HW"],
    related_codes: ["f13", "f01", "f15"], difficulty: "hard", estimated_time: "Call technician"
  },
  {
    brand: "maytag", appliance: "dryer", error_code: "f15",
    title: "Maytag Dryer F15 Error Code",
    summary: "Corrupted EEPROM data block",
    meta_description: "Maytag F15 EEPROM data error. Unplug to reset; persistent F15 needs new main electronic control.",
    meaning: "F15 means readable EEPROM returned data outside expected parameters—cycle times, temperature tables, or motor profiles may be invalid.",
    causes: ["Interrupted firmware write during a prior service flash", "Control board replaced with wrong variant", "Long-term heat exposure in a hot garage install", "Failed voltage regulator on the board corrupting writes"],
    fixes: ["Unplug overnight and retry once", "Confirm the installed control part number matches the model tech sheet", "Check for adequate ventilation around the control mount", "Avoid repeated power cycling if F15 returns instantly"],
    when_to_call_technician: "Immediate F15 on every plug-in requires the correct replacement control ordered by model and serial.",
    affected_models: ["Maytag MEDC465HW", "Maytag MGDC465HW", "Maytag MED6230HW"],
    related_codes: ["f13", "f14", "f01"], difficulty: "hard", estimated_time: "Call technician"
  }
];
